[project]
name = "exam-bash-mlops"
version = "0.1.0"
description = "MLOps pipeline for graphics card sales prediction"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.1.0",
    "numpy>=1.26.0", 
    "scikit-learn>=1.3.0",
    "xgboost>=2.0.0",
    "pytest>=7.0.0"
]
